SiteTree:
  extensions:
    - GlobalNavSiteTreeExtension
Controller:
  extensions:
    - GlobalNavControllerExtension
GlobalNav:
  snippet_path: '/assets/global-nav.html'
  css_path: '/toolbar/css/toolbar.css'
  google_search_id: 006620299726686837192:uigdvjfexik
GlobalNavTemplateProvider:
  connection_timeout: 100
  transfer_timeout: 200

Director:
  rules:
    'toolbar//$Action': 'GlobalToolbarController'
