SiteTree:
  extensions:
    - GlobalNavSiteTreeExtension
Controller:
  extensions:
    - GlobalNavControllerExtension
GlobalNav:
  snippet_path: '/assets/'
  css_file: '/toolbar/css/toolbar.css'
GlobalNavTemplateProvider:
  connection_timeout: 100
  transfer_timeout: 200
Director:
  rules:
    'toolbar//$Action': 'GlobalToolbarController'
